### PR TITLE
Add TRACE logSeverity level and trace method to logger

### PR DESCRIPTION
**Pull request by lmcnulty4**

### CODE REVIEW

**Review by philberty — COMMENTED** [review]
The only missing case is the loggerDaemonServer.cpp for shared memory handler but other wise looks good.

**Comment by lmcnulty4** [comment]
I had a look at both loggerDaemonServer.cpp and sharedMemoryLogHandler.cpp and can't see what I'm missing. There's a switch at the bottom of loggerDaemonServer.cpp but its on libevent log levels rather than ours.

**Comment by philberty** [comment]
> I had a look at both loggerDaemonServer.cpp and sharedMemoryLogHandler.cpp and can't see what I'm missing. There's a switch at the bottom of loggerDaemonServer.cpp but its on libevent log levels rather than ours.

Ah yes your right sorry about that

**Review by philberty — APPROVED** [review]

**Comment by lmcnulty4** [comment]
Sweet no worries! Cheers

**Pull request merged**
